# INFO
# For ckpts >= opensr-model version 1.0, disable 'apply_normalization'
# For ckpts >= opensr-model version 1.0, set linear_start to 0.0001 and linear_end to 0.01
# For ckpts <  opensr-model version 1.0, set linear_start to and linear_end to 0.0015 and 0.0155 respectively

# WARNING: Many of the settings, as the AE settings etc, are not used in the current version of opensr-model

# General Settings
apply_normalization: False
ckpt_version: "opensr-ldsrs2_v1_0_0.ckpt"
encode_conditioning: True

denoiser_settings: # noise settings
  linear_start: 0.0001
  linear_end: 0.015
  timesteps: 1000 # Timesteps from training
  parameterization: "eps" # ["eps" or "x0"]
  sample_eta: 0.0 # 0-1
  sample_temperature: 1.0
  sampling_steps: 100


# AE Settings
first_stage_config:
  embed_dim: 4
  double_z: true
  z_channels: 4
  resolution: 512
  in_channels: 4
  out_ch: 4
  ch: 128
  ch_mult: [1, 2, 4]
  num_res_blocks: 2
  attn_resolutions: []
  dropout: 0.0

# Denoiser Settings
cond_stage_config:
  image_size: 128
  in_channels: 8
  model_channels: 160
  out_channels: 4
  num_res_blocks: 2
  attention_resolutions: [16, 8]
  channel_mult: [1, 2, 2, 4]
  num_head_channels: 32

# other settings
other:
  concat_mode: True
  cond_stage_trainable: False
  first_stage_key: "image"
  cond_stage_key: "LR_image"

